### ISSUE TITLE
Feature Request: Automated validation with e.g. pofilter

### ISSUE THREAD

**Issue by Artoria2e5** [anthonynsimon/parrot#10]

**Comment by anthonynsimon** [comment]
Hi there, could you please describe a bit the feature request?

**Comment by Artoria2e5** [comment]
Hmm... Filters provided by [pofilter](http://docs.translatehouse.org/projects/translate-toolkit/en/latest/guides/using_pofilter.html) can be used for checking language-dependent source-translation pairs.

(You don't have to use pofilter; Weblate, for example, found it unmaintained and too buggy so they made their own: https://github.com/WeblateOrg/weblate/issues/1252#issuecomment-253529057)

**Comment by anthonynsimon** [comment]
Ah ok, so would the main purpose be to check for malformed files on export?

**Comment by Artoria2e5** [comment]
Not quite for the files, but for strings themselves.
