### ISSUE TITLE
Make service ports adjustable

### ISSUE THREAD

**Issue by PatrickWatzlawik** [anthonynsimon/parrot#11]
Hey there,

I think its a bit inconvenient that you could not specify a port for eg. the postgres server. We're running a native PostgreSQL here too, so the start.sh script failed, because the port 0.0.0.0:5432 is already in use. 

Is it possible to add a command flag to the docker-compose script?

**Comment by anthonynsimon** [comment]
I just referenced a pull request, check out the branch 'add-db-port-args' and let me know if it works properly.

Flag is '-dbp' or '--db-port' followed by the desired DB port on the host.

For example to set to port '1234':
```
$ bash scripts/start.sh --db-port 1234
```

**Comment by PatrickWatzlawik** [comment]
Yeah! Nice. Thanks for the fast response :) In my opinion this issue can be closed. Just one minor thing, which is really just the sugar, what about dynamically looking for a free db port? Like 10-20 retries before giving up?

**Comment by anthonynsimon** [comment]
Nice!

Sure, the dynamically looking for a free port can be implemented easily. What would work with the current setup is to simply select port `0` which will request a system-allocated port. You can then see the assigned port via `docker ps`. I just tried it here:

```
$ bash scripts/start.sh --db-port 0
...
$ docker ps
# Removed other data for clarity. Notice port '32773' was auto assigned.
0.0.0.0:32773->5432/tcp   parrot_db_1
```

**Comment by PatrickWatzlawik** [comment]
Cheesus, that sounds nice :)
