### ISSUE TITLE
auth endpoint "/api/v1/auth/token" not working 

### ISSUE THREAD

**Issue by e-nouri** [anthonynsimon/parrot#24]
I deployed the app on google compute engine with certificate from letsencrypt, the web-app is wokring great so far, but when i tried to auth through "/api/v1/auth/token", I have no response, i tried both methods: password and client_credentials but the app seems crashing while hitting this end point.

check the latency on each endpoint: 

> api_1    | time="2017-01-19T16:47:19Z" level=info ip=78.192.252.99 latency=1.049376ms method=GET status=200 url="/api/v1/users/self?include=projectGrants" 
> api_1    | time="2017-01-19T16:47:19Z" level=info ip=78.192.252.99 latency=1.432486ms method=GET status=200 url="/api/v1/projects/a589a977-2a4d-4411-9659-5d79601d09c4/locales/" 
> api_1    | time="2017-01-19T16:47:26Z" level=info ip=78.192.252.99 latency=145.90769ms method=POST status=200 url="/api/v1/auth/token" 
> api_1    | time="2017-01-19T16:47:44Z" level=info ip=78.192.252.99 latency=86.716352ms method=POST status=200 url="/api/v1/auth/token" 

I did not investigate yet, if you have ideas what can cause this, it may save me time.

Thank you for this great application, I was using google spearsheet before, and this is way better alternative.

Cheers,

**Comment by e-nouri** [comment]
Never mind, I was using postman, for some reason letsencrypt certificate was not validated, so i turned off the ssl validation and it worked.

**Comment by anthonynsimon** [comment]
Nice! To be sure before I close the issue, it was completely unrelated to Parrot?

It's cool to see people deploy it on different platforms. Was getting the server up and running on Google Cloud easy?
