### ISSUE TITLE
projects made using the web app (grant_type password) are not accessible from the API

### ISSUE THREAD

**Issue by e-nouri** [anthonynsimon/parrot#25]
Is there a way to change this. I mean to be able to edit the projects made using the a real user account by another client account (API, grant_type client_credentials).

**Comment by anthonynsimon** [comment]
Yes, at the moment the client_credentials can only access the 'export' endpoints for the project assigned to it. But this will be addressed soon.

The original use case is, for example, if you have a mobile game that you want to update the localization files on start, the mobile game would connect to the API with the `client_credentials` grant type and get the data, without worrying that somebody could extract the credentials and manipulate the API.

The plan is to enhance this grant type by server validated scopes. So you can grant full or partial access to your API clients.
