### ISSUE TITLE
importers needed ?

### ISSUE THREAD

**Issue by gedw99** [anthonynsimon/parrot#27]
nice project. i was about to work on something very similar.

i started to write some importers that can scrape html, svg and golang code to find text for translation, and so can contribute these.

is this something useful ?

**Comment by anthonynsimon** [comment]
Hey, yes this would be definitely something useful. Feel free to work on it if you want :)

Right now it is only possible to enter data via the API or manually via the web app (UI). It would be great to have a feature to import key-value data from various formats. Just as the exporter does (yaml, json, excel, java properties, etc...).

At the moment the only question that comes to mind is, if you import key-value data (locale translations), should only translations for previously registered keys for a given project be imported? or automatically create new keys for the project if they don't exist yet?

**Comment by gedw99** [comment]
I also was thinking about the same thing.

I feel a CLI or GUI should let the developer know and decide.
Think of it like the ' git statue's command.

When you do a scan it will check what new keys have been imported from your
source code, and tell you.
It can then create the keys for you in your other translation files.

I know this is an over simplification but the general idea if to always
have a status command with some heuristics to hint to you what is out of
sync and what to do to remedy it.

I feel a CLI and a GUI for this is worth it too.

What do you think ?

**Comment by anthonynsimon** [comment]
Yes you are right, it makes sense to have a screen or some info for previewing what's gonna happen before 'committing' the action.

**Comment by iilei** [comment]
I'd appreciate it very much.

For the conflict-resolving I think it is fine if the API does simply not alter existing translations by default and you can pass params to enforce a different behaviour (e.g `update_translations`) 

IMHO That would keep concerns separated nicely and be convenient and verbose enough 🙂

**Comment by gsantner** [comment]
Here's an example how [Crowdin](https://crowdin.com/) did such an integration.

![grafik](https://cloud.githubusercontent.com/assets/6735650/22533470/aaa06364-e8ee-11e6-8a71-4a68e18e1dc6.png)

**Comment by anthonynsimon** [comment]
Unified issue at #16
