### ISSUE TITLE
E-Mails with uppercase letters are rejected on signup 

### ISSUE THREAD

**Issue by Nick-Triller** [anthonynsimon/parrot#46]
/api/v1/users/register returns status code 422 (unprocessable entity) if the email contains uppercase letters.

**Comment by Nick-Triller** [comment]
In my opinion, the backend should store lower(signup_email) in the database. When a user tries to login, the stored email should be compared to lower(login_email).

```sql
select * from users where email=lower($LOGIN_EMAIL);
```

**Comment by anthonynsimon** [comment]
@Nick-Triller the referenced PR should solve this, thanks for reporting it.
