### ISSUE TITLE
Starting up Parrot for the first time tries to download a non-existent file.

### ISSUE THREAD

**Issue by Starz0r** [anthonynsimon/parrot#50]
I'm running Parrot on Linux Mint 18.1, all the Docker configurations seem to be working correctly, but starting up Parrot for the first time doesn't seem to work.

http://termbin.com/v5xr

In the terminal paste I linked, it seems that it's looking for a file on the Alpine Linux CDN and cannot find it, aborting the process soon after. I don't know exactly what the issue could be here, but from what I've taken a look at, it seems like it is having trouble downloading a file.

**Comment by anthonynsimon** [comment]
This looks more like an issue with the Alpine Linux repo. Were you able to solve it in the end?

Here is a related issue: https://github.com/gliderlabs/docker-alpine/issues/155
