### ISSUE TITLE
Build fails with Angular CLI 1.0.0

### ISSUE THREAD

**Issue by SlavikZ** [anthonynsimon/parrot#52]
`./scripts/buildweb.sh` script fails with latest Angular CLI 1.0.0 with lot of `Property 'xxx' is private and only accessible within class 'YYY'` errors. As far as I see it is related to https://github.com/angular/angular-cli/issues/5620 and now it is required to convert all accessed private properties to public.

Build info:
__ng --version:__
```
@angular/cli: 1.0.0
node: 7.8.0
os: linux x64
```

**Comment by iilei** [comment]
@SlavikZ does this fork work for you? https://github.com/iilei/parrot/tree/fix_build_angular_cli_v1x

**Comment by SlavikZ** [comment]
@iilei Yes, it works good, thank you!

**Comment by anthonynsimon** [comment]
Closing this as the fix provided by @iilei ws just merged #54
