### ISSUE TITLE
Display error

### ISSUE THREAD

**Issue by tqcenglish** [anthonynsimon/parrot#59]
![image](https://cloud.githubusercontent.com/assets/3167619/25510329/f67eb308-2bf1-11e7-805c-f76e386bb929.png)

Old bluma is work.  New version bluma(0.4.1) break.

[login.component.html](https://github.com/anthonynsimon/parrot/blob/master/web-app/src/app/auth/login/login.component.html)
```
<div class="container">
      <button class=>Not registered yet? Signup here</button>
 </div>
``` 
use  `contianer` get screen width.

Add locals page has some errors.

**Comment by anthonynsimon** [comment]
#57 closes this
