### ISSUE TITLE
Docker issues

### ISSUE THREAD

**Issue by eduardoinnorway** [anthonynsimon/parrot#62]
Anyone having issues with "default" machine never ending loop of trying to run, then I suggest you install this version of Docker, https://download.docker.com/mac/stable/Docker.dmg all other suggestions of solving the issue with docker, failed.

**Comment by anthonynsimon** [comment]
Thanks for reporting that @eduardoinnorway ! I will be closing the issue for now, as it seems to not be affecting anymore :)
