### ISSUE TITLE
What causes Something Went Wrong occur? 

### ISSUE THREAD

**Issue by Starz0r** [anthonynsimon/parrot#66]
I'm looking to possibly contributing to the project by removing all the hardcoded Docker integration to make it a suggestion and not a recommendation. I built the API manually, but used the script to create the front-end. This is all without Docker. Since the API connects to the server I imagined nothing would go wrong at this point, but since the front-end is not internalized, it becomes a problem since it can't see to find the API Server. This became apparent when trying to register an account and the message "Something went wrong. That's all we know." appeared. Even though going in the browser and typing out localhost:8080/api/v1/ping gives me an actual working response, the front-end does not see it. I attempted to rebuild the front-end by applying the api-address parameter as "http://127.0.0.1:8080/api/v1", but this did not change anything. Is there any reason why this would occur and how I can fix it?

Here is my dot .env file for reference
```PARROT_ENV=development
PARROT_HOST=https://parrot.example.com

PARROT_API_DB=postgres
PARROT_API_DB_URL=postgres://postgres@localhost:5432/parrot?sslmode=disable

PARROT_AUTH_ISSUER_NAME=https://github.com/anthonynsimon/parrot
PARROT_AUTH_SIGNING_KEY=secret

PARROT_DB_MIGRATION_STRATEGY=down
PARROT_DB_MIGRATIONS_DIR=./datastore/postgres/migrations```

**Comment by anthonynsimon** [comment]
Hi @Starz0r sorry for taking a while to reply!

One possibility could be that since you are using a migration strategy of `down`, you are wiping out the DB and the database has none of the tables needed by Parrot. You could try setting that up to `up` (add all tables) or `down, up` (remove existing and start clean). Here's an exmaple `.env`:

```
PARROT_ENV=development
PARROT_HOST=https://parrot.example.com

PARROT_API_DB=postgres
PARROT_API_DB_URL=postgres://postgres@db:5432/parrot?sslmode=disable

PARROT_AUTH_ISSUER_NAME=https://github.com/anthonynsimon/parrot
PARROT_AUTH_SIGNING_KEY=secret

PARROT_DB_MIGRATION_STRATEGY=up
PARROT_DB_MIGRATIONS_DIR=./datastore/postgres/migrations
```

Hopefully it's of use, even though it's a few months late ;)

**Comment by Starz0r** [comment]
@anthonynsimon I forgot I had opened this from long ago. Never thought you'd come back, so I never updated the Original Post, but if you are still around I'll post some details here.

The issue with logging in is that the front-end submits an OPTIONS header instead of POST when Registering or Logging In. I don't know if this is intended, but because of this, I could not get it to work.

I've also basically removed the process of using a .env environment by manually setting up a PostgreSQL server, compiling the front-end by hand, and manually compiling the back-end by additionally commenting out the migrations (although, I had applied those by hand to the SQL Server). The tight Docker integration is really not needed, and the hardcoded PostgreSQL SSL configuration isn't either. I can probably fix this, but it really depends if this will continue to get developed to 1.0. Would love to see this project get off the ground and finally finished.

**Comment by anthonynsimon** [comment]
@Starz0r ok thanks for the details! 

Regarding the initial `OPTIONS` request, I'm assuming it's the preflight request for cross-origin requests. But that shouldn't be causing an error. I can take a look at that to verify.

The docker integration is actually not really needed, you can start each component on it's own, that's where the `.env` file comes in handy for configuration in case your DB lies outside the containers.

The provided `docker-compose` file is mainly to make a sample setup to try things out easier. But you're right, maybe we should provide sample scripts that run the API / web-app without Docker.

I'll revisit the project, it can be improved in many regards and what you've pointed out definitely makes sense to integrate. Providing a roadmap could help to concentrate efforts towards a 1.0. Thanks for the feedback!

**Comment by Starz0r** [comment]
@anthonynsimon Decided to outline how to undockerize the project if you are still interested in working on this project :P https://github.com/anthonynsimon/parrot/issues/79

**Comment by anthonynsimon** [comment]
@Starz0r Thanks a lot for taking your time to look into improving the project! I agree with the points you mention and will assign proper labels to try to gather some help on that.

Unfortunately I'm currently a bit tight due to my day work so I haven't been able to continue working on the project constantly, but will try to push it forward in the coming months. Once again, I really appreciate your support :)

**Comment by Starz0r** [comment]
@anthonynsimon Looking forward to it, would like to help push this project forward due to love my self hosted software.
