### ISSUE TITLE
Self-hosted or not?

### ISSUE THREAD

**Issue by nonameolsson** [anthonynsimon/parrot#67]
Hi!
This is a great tool! Well done!

I don't have so much experience of Docker, but I got it working on my local machine. But we are two people working on our current project, and we want to use Parrot for translation. 

Should we both install it on our machines, and somehow share the database and connect to it from local installation? Or would it be better to host Parrot on a server somewhere?

If we want to go with the second alternative, how can we install it? I only know how to use it with Docker. Could we install docker on our server, and run Parrot there?

**Comment by anthonynsimon** [comment]
Hi @nonameolsson , sorry for taking quite a while to reply.

That should be quite easy to achieve, the `docker-compose` file is pretty much a high level view on the systems involved (nginx, a postgres DB and the Parrot API itself). You could just setup your own DB and share the credentials by editing the `.env` file for parrot (see 
 https://github.com/anthonynsimon/parrot/blob/master/parrot-api/.env). From then on it's just about starting the containers without postgres. Let me know if that works for you!
