### ISSUE TITLE
Error at build

### ISSUE THREAD

**Issue by tautf** [anthonynsimon/parrot#68]
Hey,

i tried to install parrot on my rpi.

After installation of `@angular/cli` when i try to run `./scripts/buildweb.sh` im recieving the following error:

![unbenannt](https://user-images.githubusercontent.com/18403881/28584232-45124722-716c-11e7-81fd-a68f1c722d69.PNG)

Whats the problem here?

Thank you!

**Comment by fedevegili** [comment]
Everything is working here (on master). Have you tried to update your node/npm version?

**Comment by anthonynsimon** [comment]
Hi guys, I'll be closing the issue unless it hasn't been fixed yet. In which case feel free to reopen it with more details.
