### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by peterprokop** [anthonynsimon/parrot#8]
subj

**Comment by anthonynsimon** [comment]
In terms of iOS support, do you mean the ability to export an iOS supported format or an iOS client library to wrap the Parrot API? or both? :)

**Comment by peterprokop** [comment]
`iOS client library` something similar to what [Applanga](https://applanga.com/) does. In theory I can help you with that =)

**Comment by anthonynsimon** [comment]
That'd be a great addition to the project. At some point it'd be great to have platform specific libraries. So if you want to work on the iOS client that'd be great. Any kind of contribution to the project is more than welcome.
